- name: Create EC2 instances
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_id }}"
    vpc_subnet_id: "{{ random_subnet }}"
    group: "{{ instance_name }}-sg"
    wait: yes
    instance_tags:
      Name: jumpbox
      Env: sandbox
    count_tag: 
      Name: jumpbox
      Env: sandbox
    exact_count: 1
    assign_public_ip: yes
  register: ec2

- name: Allocate a new elastic IP and associate it with an instance
  ec2_eip:
    in_vpc: yes
    region: "{{ region_name }}"
    reuse_existing_ip_allowed: yes
    device_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"
  register: instance_eip
- debug: var=instance_eip.allocation_id
  
- name: Add the newly created EC2 instance(s) to the local host group
  local_action: lineinfile 
                path="inventory/ec2"
                regexp={{ item.public_ip }} 
                insertafter="[jumpbox]" line="{{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
  with_items: "{{ instance_eip.results }}"
